### ISSUE TITLE
Enhancement: Add support for Camunda BPM

### ISSUE THREAD

**Issue by cristalp** [bserdar/jcliff#114]
We use [Camunda BPM](https://camunda.com) as a process engine within our JBoss EAP. Now I would like to configure it using Jcliff, see [the Camunda configuration documentation](https://docs.camunda.org/manual/latest/installation/full/jboss/configuration/).

I would gladly help Jcliff and contribute a solution for this. However, being a newbie, I'm not too sure how to start.

It's obvious that a lot of work goes into the rules. But can Jcliff be expanded just by writing a new rule file?

**Comment by bserdar** [comment]
@cristalp 

All the work goes into the rules. You can create a rules file for the BPM engine, add it to the list of rules, and you'll be done.

The readme should explain the rule writing process. It involves some trial/error, but once you figure it out, it is straightforward. If you're stuck, let us know.

**Comment by cristalp** [comment]
Thanks for the reply, I'll give it a try and keep you informed!

**Comment by cristalp** [comment]
Well, unfortunately Camunda doesn't offer CLI support as such.

See https://access.redhat.com/solutions/3952701
