### ISSUE TITLE
Timeout while waiting for child process to complete

### ISSUE THREAD

**Issue by NilsGriebner** [bserdar/jcliff#121]
We are running a Wildfly which contains a huge amount of deployments. This leads to slow response times during command execution. Since there are executions with hardcoded time limits in jcliff, we are facing

```
java.lang.RuntimeException: java.lang.RuntimeException: Timeout while waiting for child process to complete\n\tat com.redhat.jcliff.Cli.run(Cli.java:207)\n\tat com.redhat.jcliff.Cli.run(Cli.java:104)\n\tat com.redhat.jcliff.Ctx.runcmd(Ctx.java:102)\n\tat com.redhat.jcliff.Main.refreshServerNode(Main.java:427)\n\tat com.redhat.jcliff.Main.main(Main.java:240)\nCaused by: java.lang.RuntimeException: Timeout while waiting for child process to complete
```
Already created a hacky workaround for my personal use. I'll open a PR so that you can see which code is affected.

**Comment by rpelisse** [comment]
@NilsGriebner I've merged your PR. Should we close this issue?

**Comment by NilsGriebner** [comment]
Thanks. Yes, we can close it :)
