### ISSUE TITLE
No rules for diffs:add:/subsystem/undertow/server/default-server/http-listener

### ISSUE THREAD

**Issue by mschoepke** [bserdar/jcliff#37]
When I try to set "proxy-address-forwarding" to "true" for the default http-listener, I get this:

    No rules for diffs:add:/subsystem/undertow/server/default-server/http-listener value={"default" => {"proxy-address-forwarding" => "true"}}
    add:/subsystem/undertow/server/default-server/http-listener/default value={"proxy-address-forwarding" => "true"}
    add:/subsystem/undertow/server/default-server/http-listener/default/proxy-address-forwarding value="true"

**Comment by bserdar** [comment]
Undertow is new with widlfly, there is no support for it in jcliff yet. I
need to add this.

**Comment by mschoepke** [comment]
Works perfectly, thanks a lot!
