### ISSUE TITLE
Make replicated-cache more configurable

### ISSUE THREAD

**Issue by mschoepke** [bserdar/jcliff#39]
Please make the following configurable (in infinispan/cache-container):
 * replicated-cache
   * expiration
     * max-idle
     * life-span
     * interval

Example:

    <cache-container name="bla" default-cache="blaCache" jndi-name="java:jboss/infinispan/container/bla" start="EAGER" module="com.foo.bla.cache">
        <transport stack="tcp" cluster="bla-cache-cluster" lock-timeout="60000"/>
        <replicated-cache name="blaCache" batching="true" mode="SYNC">
            <locking isolation="REPEATABLE_READ"/>
            <eviction strategy="NONE" max-entries="1000"/>
            <expiration max-idle="600000" lifespan="288000000" interval="500"/>
        </replicated-cache>
        [...]
    </cache-container>

Thanks.

**Comment by bserdar** [comment]
This should already work. Look at the new example for infinispan under testscripts. The trick is:

...
replicated-cache => {
    expiration => {
        EXPIRATION => {
              max-idle => ...

That is: use the additional object EXPIRATION for expiration, EVICTION for eviction, and LOCKING for locking, Names have to be those, it doesn't accept any other name.
