### ISSUE TITLE
No rules for diffs:add:/configuration/filter/gzip/name value="gzipFilter"

### ISSUE THREAD

**Issue by mschoepke** [bserdar/jcliff#40]
I'm trying to add

    <gzip name="gzipFilter"/>

under the filters section of undertow.

This is my jcliff template:

    { "undertow" =>
      { "configuration" =>
        { "filter" =>
          { "gzip" =>
            { "name" => "gzipFilter" }
          }
        }
      }
    }

But the result is: No rules for diffs:add:/configuration/filter/gzip/name value="gzipFilter".

Could you please add the necessary rules?

**Comment by bserdar** [comment]
Added in v2.9.12

**Comment by mschoepke** [comment]
Thanks!
