### ISSUE TITLE
XA Datasources not working with Wildfly 8.2.0.Final

### ISSUE THREAD

**Issue by fuero** [bserdar/jcliff#41]
Despite jcliff 2.9.11 running JBoss CLI in batch mode, wildfly 8.2.0.Final refused adding a XA datasource with

> Exception in thread "main" java.lang.RuntimeException: Operation failed:{"JBAS014653: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => "JBAS010469: At least one xa-datasource-property 
is required for an xa-datasource"}}

Using this in `/usr/share/jcliff-2.9.11/rules/xadatasource` works:

    add.rule.1=xa-data-source add --name=${name(.)} --jndi-name=${value(jndi-name)} --driver-name=${value(driver-name)} --xa-datasource-properties=[{URL=${value(xa-datasource-properties/URL/value)}}]
    add.rule.2=if result.value==false of /subsystem=datasources/xa-datasource=${name(.)}:read-resource
    add.rule.3=xa-data-source enable --name=${name(.)}

**Comment by bserdar** [comment]
Apparently this has been changed in wildfly. URL wasn't required before. It appears to be a backwards compatible change, so I'm updating the rule. Thanks.
