### ISSUE TITLE
Add support for datasource properties

### ISSUE THREAD

**Issue by mschoepke** [bserdar/jcliff#54]
Please add support for the following properties of a datasource:

* validation
  * check-valid-connection-sql
  * validate-on-match
  * background-validation
  * background-validation-millis
  * ...
* timeout
  * set-tx-query-timeout
  * blocking-timeout-millis
  * idle-timeout-minutes
  * query-timeout
  * use-try-lock
  * allocation-retry
  * allocation-retry-wait-millis
  * ...

**Comment by bserdar** [comment]
These are not JDBC driver properties, they are datasource properties, and
setting them is already supported. Please let me know if this doesn't work.
Thanks.

**Comment by mschoepke** [comment]
Yes, it works fine, thanks.

**Comment by MarS919** [comment]
I just found out that using datasource properties in jcliff breaks its Idempotence. jcliff will reload every time it runs.

Example: background-validation-millis should be set to 30000. If I read the log correctly, it finds it to be set to 30000**L**. Don't know where the L comes from. Of course, it will write the attribute again to be 30000.

Any clue?

**Comment by bserdar** [comment]
It is probably because of automatic type conversion. You set some value to
30000, it is internally a long value, so it shows up as 30000L (L means
"long"), jcliff compares the nodes and sees "30000"!="30000L", and applies
the rule again.

If jboss-cli says it is 30000L, then set it to 30000L in your configuration
file, and it should work once. I'll try to find a way to change the
comparison algorithm to ignore such syntax differences.

**Comment by MarS919** [comment]
No, jboss-cli says it's 30000. Just jcliff reads it as 30000L.

Setting it to 30000L in my configuration results in
```
Exception in thread "main" java.io.IOException: Invalid character: L
```

**Comment by bserdar** [comment]
ok, i'll check

**Comment by bserdar** [comment]
Please try with 2.10.13.

**Comment by MarS919** [comment]
Thanks for the new version, but the issue remains the same. Tell me when you need more information from me.

**Comment by bserdar** [comment]
Can you send me the full execution log when jcliff is run with this
configuration file causing the problem? Run jcliff with -v, and remove any
passwords in the output please.

Thanks.
