### ISSUE TITLE
wildfly doesn't reload although necessary

### ISSUE THREAD

**Issue by juame** [bserdar/jcliff#56]
Unfortunately, it's not working when we use jcliff like this to deploy a jdbc driver and an app (.war) that depends on the driver:
```
/usr/bin/jcliff --cli=/opt/wildfly/bin/jboss-cli.sh \
--controller=127.0.0.1:9990 --user=mgmt-users --password=very-secret-password \
--reload /etc/jcliff/* -v
```
The reload happens at the end of the jcliff run, which fails the deployment of the app.

We do somehow expect following sequence: driver --> reload --> deploy app.
Do you know if this is a bug in jcliff? Thanks.

**Comment by juame** [comment]
Correction: Driver or Datasource...

**Comment by bserdar** [comment]
Try v2.10.5. I added :reload after adding a new jdbc driver and datasource.

**Comment by mschoepke** [comment]
It looks like jcliff adds the password and the username of a datasource in a separate step. Could it be that jcliff should reload **after adding these attributes**?

We have the issue that the deployment of the app fails because the database connection is done without username/password.

**Comment by bserdar** [comment]
Should we :reload *before* app deployments?

**Comment by mschoepke** [comment]
Would make sense for our scenario, but I don't know if it interferes with how other people are using jcliff.

**Comment by bserdar** [comment]
--reload now reloads after each subsystem if necessary.

**Comment by mschoepke** [comment]
Works like a charm. Thanks!
