### ISSUE TITLE
xadatasource precedence incorrect? 

### ISSUE THREAD

**Issue by shaunrampersad** [bserdar/jcliff#68]
Hi
I've upgraded jcliff from 2.10.8 to 2.11.3 and the xadatasource rules file has changed. The precedence for adding xa-datasource-properties has changed

From addXAProperty.precedence=70
To addXAProperty.precedence=10

This causes a failure to add an xa-datasource since jcliff tries to add the properties first before creating the datasource. 

The error in the log is
2016-08-02 13:45:20:0731: Return:{
    "outcome" => "failed",
    "failure-description" => "JBAS014766: Resource [
    (\"subsystem\" => \"datasources\"),
    (\"xa-data-source\" => \"ds_xatest2\")
] does not exist; a resource at address [
    (\"subsystem\" => \"datasources\"),
    (\"xa-data-source\" => \"ds_xatest2\"),
    (\"xa-datasource-properties\" => \"DatabaseName\")
] cannot be created until all ancestor resources have been added",
    "rolled-back" => true
}

Replacing the rule file with the one from v2.10.8 allows the config to proceed.

This is the current config file
{ "xadatasource" => {
  "ds_xatest2" => {
        "enabled" => "true",
        "jndi-name" => "java:/jboss/datasources/test1",
        "pool-name" => "java:/jboss/datasources/test2",
        "driver-name" => "postgresql-jdbc42",
        "security-domain" => "MytestDS",
        "xa-datasource-properties" => {
            "DatabaseName" => { "value" => "mydb" },
            "ServerName" => { "value" => "myserver" },
        }
     }
  }
}

Thanks
Shaun

**Comment by shaunrampersad** [comment]
FYI. I've downgraded to 2.10.9 which includes the reconnect-delay option which is why I upgraded in the first place. 
The downgrade has the correct rule precedence and now I can configure jboss successfully. It might be that there is a new config I'm missing somewhere for the latest version.

**Comment by bserdar** [comment]
Should be fixed now.
